FROM golang:1.21.4-bullseye

WORKDIR /go/src/app

RUN apt update && apt install -y \
    git \
    sqlite3 \
    && rm -rf /var/lib/apt/lists/*

COPY go.mod go.sum ./

RUN go mod download

RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

COPY . .

CMD go run main.go
